acme_cert_ca_new:
    path: /app/panel/ca/new
    defaults: { _controller: AcmeCertBundle:RootCa:new }
acme_cert_download:
    path: /app/panel/ca/download/{repository}
    defaults: { _controller: AcmeCertBundle:RootCa:getCertList, repository: 'AcmeCertBundle:CA'}
user_area_client_cert:
    path: /app/panel/ca/cert
    defaults: { _controller: AcmeCertBundle:ClientCert:newSignedCert }
user_area_new_client_cert:
    path: /app/panel/ca/newcert/{password}
    defaults: { _controller: AcmeCertBundle:ClientCert:newSignedCert, password: null }
acme_client_cert_download:
    path: /app/panel/cert/download/{repository}
    defaults: { _controller: AcmeCertBundle:RootCa:getCertList, repository: 'AcmeCertBundle:ClientCertificate'}
