acme_cert_ca_new:
    path: /app/panel/ca/new
    defaults: { _controller: AcmeCertBundle:RootCa:new }
acme_cert_download:
    path: /app/panel/ca/download
    defaults: { _controller: AcmeCertBundle:RootCa:getCaFromDb }
