acme_cert_ca_new:
    path: /app/panel/ca/new
    defaults: { _controller: AcmeCertBundle:RootCa:new }
acme_cert_download:
    path: /app/panel/ca/download/{repository}/{id}
    defaults: { _controller: AcmeCertBundle:RootCa:getCertList, repository: 'CA', id: 1}
user_area_client_cert:
    path: /app/panel/ca/cert
    defaults: { _controller: AcmeCertBundle:ClientCert:newSignedCert }
user_area_new_client_cert:
    path: /app/panel/ca/newcert/{password}
    defaults: { _controller: AcmeCertBundle:ClientCert:newSignedCert, password: null }
acme_client_cert_download:
    path: /app/panel/cert/download/{repository}/{id}
    defaults: { _controller: AcmeCertBundle:RootCa:getCertList, repository: 'Client', id: 1}
acme_client_cert_unset:
    path: /app/panel/cert/unset/{id}
    defaults: { _controller: AcmeCertBundle:ClientCert:unsetCert }
