parameters:
#    acme_cert.example.class: Acme\CertBundle\Example

services:
#    acme_cert.example:
#        class: %acme_cert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
