acme_site:
    resource: "@AcmeSiteBundle/Resources/config/routing.yml"
    prefix:   /

acme_form:
    resource: "@AcmeFormBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

