acme_site_homepage:
    path:     /
    defaults: { _controller: AcmeSiteBundle:Default:index }
user_area_login_check:
    path: /check
    defaults: { _controller: AcmeSiteBundle:Islogged:login_check }
user_area_root_ca_site:
    path: /app/panel/ca
    defaults: { _controller: AcmeSiteBundle:Default:caSite }

