acme_site_homepage:
    path:     /
    defaults: { _controller: AcmeSiteBundle:Default:index }
user_area_login_check:
    path: /check
    defaults: { _controller: AcmeSiteBundle:Islogged:login_check }

    
