parameters:
#    acme_form.example.class: Acme\FormBundle\Example

services:
#    acme_form.example:
#        class: %acme_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
