acme_user_register:
    path:     ^/app/register
    defaults: { _controller: AcmeUserBundle:Register:register }

## STREFA LOGOWANIA ##
login_check:
    pattern: /app/login_check

acme_user_login:
    path:     /app/login
    #defaults: { _controller: AcmeSiteBundle:Default:loginRegister }
    defaults: { _controller: AcmeUserBundle:Register:register }

logout:
    pattern: /app/logout

## ======================== ##

acme_user_panel:
    path:    /app/panel
    defaults: { _controller: AcmeUserBundle:Account:index }
