acme_user_register:
    path:     /app/register
    defaults: { _controller: AcmeUserBundle:Register:register }

## STREFA LOGOWANIA ##
login_check:
    pattern: /app/login_check

acme_user_login:
    path:     /app/login
    defaults: { _controller: AcmeUserBundle:Login:login }

logout:
    pattern: /app/logout

xxx:
    path:    /app/
    defaults: { _controller: AcmeSiteBundle:Default:index }

## ======================== ##

acme_user_main_page:
    path:    /app/account
    defaults: { _controller: AcmeUserBundle:Account:index }
